name: Altersvorsorge
favicon: null
layout_spectrum: 0.49882
typography_spectrum: 0.7531171762384474
title: Wissenswerte Informationen rund um die Altersvorsorge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fd1b14'
    - '#121212'
    - '#5e5e5e'
    - '#ffb301'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
