name: Altersvorsorge
favicon: null
layout_spectrum: 0.75542
typography_spectrum: 0.7531171762384474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fd1a13'
    - '#5d5d5d'
    - '#ffb201'
    - '#303030'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
