name: Altersvorsorge
favicon: null
layout_spectrum: 0.8758195578120649
typography_spectrum: 0.7531171762384474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8742551929317415
  lightness: 0.42261216836050153
  saturation: 0.5491927051916718
  rhythmicContrast: 0.26710821292363107
purpose: []
