analytics:
  google: UA-73438517-1
color:
  brandColors:
    - '#000000'
    - '#fd1a13'
    - '#5d5d5d'
    - '#ffb201'
    - '#303030'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.75542
name: Rund um die Altersvorsorge
opengraph: {}
purpose: []
typography_spectrum: 0.7531171762384474
