analytics: {}
color:
  brandColors:
    - '#fd1b14'
    - '#121212'
    - '#5e5e5e'
    - '#ffb301'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 1
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.205163
name: Altersvorsorge
opengraph: {}
purpose: []
typography_spectrum: 0.7531171762384474
