name: Rund um die Altersvorsorge
favicon: null
layout_spectrum: 0.75542
typography_spectrum: 0.7531171762384474
title: Wissenswerte Informationen rund um die Altersvorsorge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73438517-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fd1a13'
    - '#5d5d5d'
    - '#ffb201'
    - '#303030'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
